import { Routes } from '@angular/router';
import { MenuOpcionesComponent } from './views/medellin-menu/medellin-menu.component';
import { InicioComponent } from './views/inicio/inicio.component';
import { CamionesComponent } from './views/camiones/camiones.component';
import { SensoresRuidoComponent } from './views/sensores-ruido/sensores-ruido.component';
import { ReportesMedicos } from './views/reportes-medicos/reportesmed.component';
import { PuntosWifi } from './views/puntos-wifi/puntoswifi.component';
import { Vamosmed } from './views/vamosmedellin/vamosmed.component';
import { Pqrsd } from './views/PQRSD/pqrsd.component';
import { Turismo } from './views/turismo/turismo.component';
import { Siata } from './views/siata/siata.component';
import { MapasCamiones } from './views/mapas-camiones/mapas-camiones.component';
import { ReportesMedMap } from './views/reportes-medmap/reportesmed-map.component';
import { WifiMaps } from './views/wifi-maps/wifi-maps.component';
import { VamosMedMap } from './views/vamosmedmap/vamosmed-map.component';
import { SensoresMap } from './views/sensoresmap/sensoresmap.component';
import { TurismoMaps } from './views/turismomaps/turismomaps.component';
import { SiataMaps } from './views/siatamaps/siatamaps.component';

export const routes: Routes = [
  { path: '', component: MenuOpcionesComponent },
  { path: 'inicio', component: InicioComponent },
  { path: 'ambiente/gestion-residuos/camiones', component: CamionesComponent },
  { path: 'ambiente/calidad-ambiental/sensores-ruido', component: SensoresRuidoComponent },
  { path: 'ambiente/calidad-ambiental/tablero-siata', component: Siata },
  { path: 'gobernanza/reportesmed-tablero', component: ReportesMedicos },
  { path: 'desarrollo-economico/transformacion-digital/tablero', component: PuntosWifi },
  { path: 'movilidad-inteligente/vamosmed-tablero', component: Vamosmed },
  { path: 'gobernanza/pqrs-tablero', component: Pqrsd },
  { path: 'calidad-vida/turismo-tablero', component: Turismo },
  { path: 'mapas/camiones', component: MapasCamiones },
  { path: 'mapas/reportesmed', component: ReportesMedMap },  
  { path: 'mapas/puntos-wifi', component: WifiMaps },  
  { path: 'mapas/vamosmed', component: VamosMedMap }, 
  { path: 'mapas/sensores-ruido', component: SensoresMap }, 
  { path: 'mapas/turismo', component: TurismoMaps }, 
  { path: 'mapas/siata', component: SiataMaps }
];
